---
Name: visio-analytics
After:
  - 'framework/*'
  - 'cms/*'
---

Page_Controller:
  extensions:
    - VisioAnalyticsSiteTreeExtension

SiteConfig:
  extensions:
    - VisioAnalyticsSiteConfigExtension
